EXE_PATH = 'tools\\opensmile-2.3.0\\bin\Win32\SMILExtract_Release.exe'
CONFIG_PATH = 'tools\\opensmile-2.3.0\\config\\gemaps\\eGeMAPSv01a.conf'
IEMOCAP_FOLDER = 'datasets\\iemocap_audios\\'
CREMAD_FOLDER = 'datasets\\crema-d_audios\\'
EMODB_FOLDER = 'datasets\\emodb\\wav\\'
RAVDESS_FOLDER = 'datasets\\ravdess\\'
SAVEE_FOLDER = 'datasets\\savee\\ALL\\'
TESS_FOLDER = 'datasets\\tess\\'